// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMprtKCf-ED7GJTOt9OkpNLvxTfMlv-BQ',
    appId: '1:241307564084:web:21010fc40d7cd446623261',
    messagingSenderId: '241307564084',
    projectId: 'appalimentos-933c7',
    authDomain: 'appalimentos-933c7.firebaseapp.com',
    storageBucket: 'appalimentos-933c7.appspot.com',
    measurementId: 'G-3QZR6K3H09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWGVhAmtey0m_xAX6cb9hef99SKPIFSM',
    appId: '1:241307564084:android:aea60106f5a0d1d0623261',
    messagingSenderId: '241307564084',
    projectId: 'appalimentos-933c7',
    storageBucket: 'appalimentos-933c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvfzq_Mss9f_HWfE3v8Q1ViBYweGusyk',
    appId: '1:241307564084:ios:7296ac1dbba856d8623261',
    messagingSenderId: '241307564084',
    projectId: 'appalimentos-933c7',
    storageBucket: 'appalimentos-933c7.appspot.com',
    iosBundleId: 'com.example.alimentosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRvfzq_Mss9f_HWfE3v8Q1ViBYweGusyk',
    appId: '1:241307564084:ios:7296ac1dbba856d8623261',
    messagingSenderId: '241307564084',
    projectId: 'appalimentos-933c7',
    storageBucket: 'appalimentos-933c7.appspot.com',
    iosBundleId: 'com.example.alimentosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMprtKCf-ED7GJTOt9OkpNLvxTfMlv-BQ',
    appId: '1:241307564084:web:91a2e7102e0391b8623261',
    messagingSenderId: '241307564084',
    projectId: 'appalimentos-933c7',
    authDomain: 'appalimentos-933c7.firebaseapp.com',
    storageBucket: 'appalimentos-933c7.appspot.com',
    measurementId: 'G-VV61HSG405',
  );
}
